// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwFwfw7ydOFuw3g1TeHDcw-lDqdj-5se0',
    appId: '1:173454341799:web:b57d7e1eb5e75397490d82',
    messagingSenderId: '173454341799',
    projectId: 'space-x-9b8e1',
    authDomain: 'space-x-9b8e1.firebaseapp.com',
    storageBucket: 'space-x-9b8e1.appspot.com',
    measurementId: 'G-7ESFLX9M6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdBUVak7wAuRzSdxcdjX7Jrm2c5p8FNyU',
    appId: '1:173454341799:android:054df75d22641382490d82',
    messagingSenderId: '173454341799',
    projectId: 'space-x-9b8e1',
    storageBucket: 'space-x-9b8e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVjRwvRwe_awYv6jB4m5s_1oexvDf8hi4',
    appId: '1:173454341799:ios:d1cef4776e216ccc490d82',
    messagingSenderId: '173454341799',
    projectId: 'space-x-9b8e1',
    storageBucket: 'space-x-9b8e1.appspot.com',
    iosBundleId: 'com.example.spacex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVjRwvRwe_awYv6jB4m5s_1oexvDf8hi4',
    appId: '1:173454341799:ios:d1cef4776e216ccc490d82',
    messagingSenderId: '173454341799',
    projectId: 'space-x-9b8e1',
    storageBucket: 'space-x-9b8e1.appspot.com',
    iosBundleId: 'com.example.spacex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwFwfw7ydOFuw3g1TeHDcw-lDqdj-5se0',
    appId: '1:173454341799:web:d72a67439c73c08c490d82',
    messagingSenderId: '173454341799',
    projectId: 'space-x-9b8e1',
    authDomain: 'space-x-9b8e1.firebaseapp.com',
    storageBucket: 'space-x-9b8e1.appspot.com',
    measurementId: 'G-87NKS9D4BK',
  );
}
